[env]
# Workaround to delude tmux
TERM =  "xterm-256color"

[window]
startup_mode = "Maximized"
padding = { x = 5, y = 5 }

[font]
size = 14
normal = { family = "RobotoMono Nerd Font", style = "Regular" }

[keyboard]
bindings = [
    { key = "Right", mods = "Alt", chars = "\u001BF" },
    { key = "Left",  mods = "Alt", chars = "\u001BB" },
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },
]

# One Dark coloscheme
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
